### PR TITLE
Doesn't lock Yarn Version on deploy

### PR DESCRIPTION
**Pull request by raphamorim**
"JavaScript Universe is constantly changing"

### CODE REVIEW

**Comment by raphamorim** [comment]
@andrestc check it out.

**Comment by lucasts** [comment]
This should work around yarnpkg/yarn#1462 when no version is specified.
@raphamorim Do you had any luck with new  yarn versions and `NODE_ENV=production`?

**Comment by raphamorim** [comment]
Not with 0.17.0~0.20.0
I ain't tested with greater than 0.20.0. I'll test and report here

**Comment by rwillrich** [comment]
Running `NODE_ENV=production yarn install --prod` in our project locally it works with no problems:

```
$ NODE_ENV=production yarn install --prod
yarn install v0.24.6
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-smart-app-banner@0.3.0" has incorrect peer dependency "react@~0.14".
warning "react-smart-app-banner@0.3.0" has incorrect peer dependency "react-dom@~0.14".
warning "pure-render-decorator@0.2.0" has incorrect peer dependency "react@^0.14.0".
warning "react-addons-shallow-compare@0.14.8" has incorrect peer dependency "react@^0.14.8".
[4/4] 📃  Building fresh packages...
✨  Done in 11.55s.
```

As you can see in the log above, I'm using the last version `0.24.6`.

**Comment by andrestc** [comment]
LGTM, thanks

**Comment by lucasts** [comment]
we could default to yarn `0.24.6` instead of `0.16.1`

**Pull request merged**
