### PR TITLE
Update ruby enviroment

### PR DESCRIPTION
**Pull request by gwmoura**
* added dependencies packages for run most ruby projects 
* install ruby based ruby version in Gemfile or .ruby-version
* added ruby env vars in `/home/ubuntu/.bashrc` and `/etc/profile`
* added ruby 2.2.3 as default
* removed regex to get pure version

### CODE REVIEW

**Comment by gwmoura** [comment]
For tests I used:
* this image - https://hub.docker.com/r/gwmoura/tsuru-ruby/
* this repo - https://github.com/gwmoura/hellosinatra
* Online app - http://hellosinatra.gcodetecapp.com/

**Comment by gwmoura** [comment]
@fsouza what you think?

**Comment by andrewsmedina** [comment]
@gwmoura why `nodejs` and `python-software-properties` are required for ruby platform?

**Comment by gwmoura** [comment]
@andrewsmedina `nodejs` is a dependency for rails apps, `python-sotware-properties` I don't know why, I use this tutorial https://gorails.com/setup/ubuntu/14.04 as base, and one of packages to need install is `python-software-properties`.

If you want, I can test the image without this 2 packages.

**Comment by gwmoura** [comment]
@andrewsmedina `python-software-properties` was removed. 
As you talked, `nodejs` is used in rails apps for the asset pipeline and `python-software-properties` is used to install add-apt-repository, but not is used in the tutorial for ruby's setup

**Comment by andrewsmedina** [comment]
@gwmoura thank you!

I believe that a future improvement in the ruby platform is to have a way to get the ruby binaries from a custom location address.

**Comment by gwmoura** [comment]
@andrewsmedina we get the ruby binary from personalized heroku url: `https://heroku-buildpack-ruby.s3.amazonaws.com/cedar-14/ruby-$RUBY_VERSION.tgz`.

You think in another alternative?

**Comment by fsouza** [comment]
@gwmoura he meant being able of customizing the part ``https://heroku-buildpack-ruby.s3.amazonaws.com/cedar-14``, in case the company wants to run a local proxy, for example.

**Comment by gwmoura** [comment]
oh! Great! I go think in something

**Pull request merged**
