### PR TITLE
go: don't run go get if vendored

### PR DESCRIPTION
**Pull request by guilhermebr**

### CODE REVIEW

**Comment by cezarsa** [comment]
Isn't simply ignoring the errors in `go get` as we already do enough? I can see situation where the vendor directory exists but isn't populated and this may cause unexpected errors.

**Comment by guilhermebr** [comment]
Without this, every deploy will go get everything, increasing the deploy time, network i/o and image size... 

maybe instead of check the vendor directory, set an env to bypass `go get`?
or if need run `go get` even having vendor directory, run as a build hook...

**Comment by ggarnier** [comment]
I like the idea of using an env var. We could skip `go get` by default if `vendor` directory exists, and run it only if some env var is set

**Comment by cezarsa** [comment]
@guilhermebr So I think the problem is not about `go get` in itself, it's more about using `./...`, isn't it? Wouldn't changing it to `go get -d .` be enough them? We already require the main package to be in the root directory (due to the go build command later) and running `go get -d .` won't download anything if everything required by the package is already in the vendor directory.

I don't like the idea of adding yet another env variable to make this configurable unless it's absolutely necessary, as it's another thing users have to learn to be able to use the platform.

**Comment by guilhermebr** [comment]
@cezarsa awesome! tested here and works very well!
I will update the PR

**Comment by jnana-rb** [comment]
@cezarsa even having `go get -d .` is troublesome. Users may be having private repos and since there is no way of providing credentials, other than having it in the platform build files and none like it to be hardcoded. I would prefer the env method as it gives some control to the app user.

**Comment by cezarsa** [comment]
@jnana-rb The `go get -d .` call is made between calls to `set +e` and `set -e`. This will cause any errors due to invalid credentials or something similar to be ignored. We'll only log the error messages but the deploy process will continue as if nothing have happened, these log message might even be helpful on figuring something is missing from vendor. Would this behavior fulfill your requirements?

**Comment by jnana-rb** [comment]
`go get -d .` might be better than `go get ./...`, but it doesn't solve the problem. As I said, to fetch private libraries or repos, the problem still exists.

**Pull request merged**
